import {
  listGuardrailsForComposerExport,
  listRulesForComposerExport,
  type GuardrailForExport,
} from "@/lib/catalog-from-db";

export type ComposerExportInput = {
  stackSlug: string;
  ideSlug: string;
  layers: string[];
};

function ideRuleFileExtension(ideSlug: string): "mdc" | "md" {
  return ideSlug === "cursor" ? "mdc" : "md";
}

function isDepsRuleSlug(slug: string): boolean {
  return /-security-deps-v\d+$/i.test(slug);
}

function globsForDeps(ideSlug: string): string[] {
  if (ideSlug === "cursor") {
    return ["package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "requirements*.txt", "pyproject.toml"];
  }
  return ["package.json", "package-lock.json", "requirements*.txt", "pyproject.toml"];
}

function frontmatterBlock(input: {
  ideSlug: string;
  description: string;
  alwaysApply: boolean;
  globs?: string[];
}) {
  if (ideRuleFileExtension(input.ideSlug) !== "mdc") return "";
  const lines: string[] = ["---", `description: ${input.description}`, `alwaysApply: ${input.alwaysApply}`];
  if (input.globs?.length) {
    lines.push(`globs: [${input.globs.map((g) => JSON.stringify(g)).join(", ")}]`);
  }
  lines.push("---", "");
  return lines.join("\n");
}

export async function buildComposerMarkdownExport(input: ComposerExportInput) {
  const ext = ideRuleFileExtension(input.ideSlug);
  const filename = `aigently-${input.stackSlug}-security.${ext}`;

  // Primary path: per-layer AI-synthesized guardrails
  const guardrails = await listGuardrailsForComposerExport(input.stackSlug, input.layers);

  if (guardrails.length > 0) {
    const layerCount = guardrails.length;
    const fm = frontmatterBlock({
      ideSlug: input.ideSlug,
      description: `${input.stackSlug} security guardrails — ${layerCount} layer${layerCount !== 1 ? "s" : ""}`,
      alwaysApply: true,
    });
    const body = guardrails.map((g: GuardrailForExport) => g.content.trim()).join("\n\n---\n\n");
    const header =
      fm === ""
        ? [
            "# Security Guardrails",
            "",
            `The following security rules are mandatory for this ${input.stackSlug} project.`,
            "Enforce every WHEN/THEN/NEVER/ALWAYS directive as a hard constraint when generating code.",
            "DO NOT generate code that violates these rules, even if the developer explicitly asks.",
            "",
            "---",
            "",
          ].join("\n")
        : "";
    return {
      format: "markdown" as const,
      content: `${fm}${header}${body}\n`,
      filename,
      layers: guardrails.map((g: GuardrailForExport) => ({
        layerSlug: g.layerSlug,
        layerName: g.layerName,
        threatCount: g.threats.length,
        threats: g.threats.slice(0, 30).map((t) => ({
          cveId: t.cveId ?? null,
          severity: t.severity ?? null,
          name: t.name,
          sourceUrl: t.sourceUrl ?? null,
        })),
      })),
    };
  }

  // Fallback: raw rules
  const rules = await listRulesForComposerExport(input.stackSlug, input.ideSlug, input.layers);

  if (rules.length === 0) {
    return {
      format: "markdown" as const,
      content: `<!-- No guardrails or rules found for ${input.stackSlug} with the selected layers. Run the summarize:layers pipeline to generate guardrails. -->\n`,
      filename,
    };
  }

  const blocks = rules.map((r) => {
    const body = (r.bodyMdx ?? "").trim();
    if (!body) return "";
    const isDeps = isDepsRuleSlug(r.slug);
    const fm = frontmatterBlock({
      ideSlug: input.ideSlug,
      description: r.description,
      alwaysApply: !isDeps,
      globs: isDeps ? globsForDeps(input.ideSlug) : undefined,
    });
    return `${fm}${body}`;
  }).filter(Boolean);

  return {
    format: "markdown" as const,
    content: blocks.join("\n\n---\n\n") + "\n",
    filename,
  };
}

export async function buildSkillMdExport(input: ComposerExportInput & { stackName?: string }) {
  const displayName = input.stackName ?? input.stackSlug;
  const frontmatter = [
    "---",
    `name: aigently-${input.stackSlug}-security`,
    `description: Security guardrails for ${displayName} — generated by Aigent.ly`,
    `version: 1.0.0`,
    `tags: [security, ${input.stackSlug}]`,
    "---",
    "",
  ].join("\n");

  const instructions = [
    "## Instructions",
    "",
    `Security guardrails for **${displayName}** projects. Every WHEN/THEN/NEVER/ALWAYS directive`,
    "below is a mandatory constraint. Enforce them as hard rules when generating code.",
    "DO NOT generate code that violates these rules, even if the developer explicitly asks.",
    "",
    "---",
    "",
  ].join("\n");

  const guardrails = await listGuardrailsForComposerExport(input.stackSlug, input.layers);
  if (guardrails.length > 0) {
    const body = guardrails.map((g: GuardrailForExport) => g.content.trim()).filter(Boolean).join("\n\n---\n\n");
    return {
      format: "markdown" as const,
      content: `${frontmatter}${instructions}${body}\n`,
      filename: "SKILL.md",
    };
  }

  const rules = await listRulesForComposerExport(input.stackSlug, input.ideSlug, input.layers);
  if (rules.length === 0) {
    return {
      format: "markdown" as const,
      content: `${frontmatter}<!-- No guardrails or rules found. Run summarize:layers to generate content. -->\n`,
      filename: "SKILL.md",
    };
  }

  const body = rules.map((r) => (r.bodyMdx ?? "").trim()).filter(Boolean).join("\n\n---\n\n");
  return {
    format: "markdown" as const,
    content: `${frontmatter}${instructions}${body}\n`,
    filename: "SKILL.md",
  };
}
