import { listRulesForComposerExport } from "../repos/rulesRepo.js";

export type ComposerExportInput = {
  stackSlug: string;
  ideSlug: string;
  layers: string[];
};

function ideRuleFileExtension(ideSlug: string): "mdc" | "md" {
  // Cursor uses `.mdc` for rule files; others can consume plain markdown.
  return ideSlug === "cursor" ? "mdc" : "md";
}

function isPatternsRuleSlug(slug: string): boolean {
  return /-security-patterns-v\d+$/i.test(slug);
}

function isDepsRuleSlug(slug: string): boolean {
  return /-security-deps-v\d+$/i.test(slug);
}

function globsForDeps(ideSlug: string): string[] {
  // Minimal safe default: only show when editing dependency manifests.
  // (Cursor supports `.mdc` frontmatter; other IDEs still benefit from the intent.)
  if (ideSlug === "cursor") {
    return ["package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "requirements*.txt", "pyproject.toml"];
  }
  return ["package.json", "package-lock.json", "requirements*.txt", "pyproject.toml"];
}

function frontmatterBlock(input: {
  ideSlug: string;
  description: string;
  alwaysApply: boolean;
  globs?: string[];
}) {
  if (ideRuleFileExtension(input.ideSlug) !== "mdc") return "";
  const lines: string[] = ["---", `description: ${input.description}`, `alwaysApply: ${input.alwaysApply}`];
  if (input.globs?.length) {
    lines.push(`globs: [${input.globs.map((g) => JSON.stringify(g)).join(", ")}]`);
  }
  lines.push("---", "");
  return lines.join("\n");
}

export async function buildComposerMarkdownExport(input: ComposerExportInput) {
  const rules = await listRulesForComposerExport(
    input.stackSlug,
    input.ideSlug,
    input.layers
  );

  const header = [
    `<!-- Aigent.ly composer export -->`,
    `Stack: ${input.stackSlug}`,
    `IDE: ${input.ideSlug}`,
    input.layers.length ? `Layers: ${input.layers.join(", ")}` : `Layers: (all)`,
    ``,
    `---`,
    ``,
  ].join("\n");

  if (rules.length === 0) {
    return {
      format: "markdown" as const,
      content: `${header}_No matching rules in the catalog for this configuration._\n`,
      filename: `aigently-rules-${input.stackSlug}-${input.ideSlug}.md`,
    };
  }

  const ext = ideRuleFileExtension(input.ideSlug);
  const blocks = rules.map((r) => {
    const body = (r.bodyMdx ?? "").trim() || `_No body for **${r.slug}**._`;
    const isPatterns = isPatternsRuleSlug(r.slug);
    const isDeps = isDepsRuleSlug(r.slug);
    const fileBase = isPatterns ? "security-patterns" : isDeps ? "security-deps" : r.slug;
    const filename = `aigently-${input.stackSlug}-${fileBase}.${ext}`;
    const fm = frontmatterBlock({
      ideSlug: input.ideSlug,
      description: r.description,
      alwaysApply: isDeps ? false : true,
      globs: isDeps ? globsForDeps(input.ideSlug) : undefined,
    });
    const fileContent = `${fm}${body}\n`;
    return [
      `## ${r.name}`,
      `**Slug:** \`${r.slug}\` · **Version:** ${r.version}`,
      `**File:** \`${filename}\``,
      ``,
      "```",
      fileContent.trimEnd(),
      "```",
      ``,
      "---",
      "",
    ].join("\n");
  });

  return {
    format: "markdown" as const,
    content: `${header}${blocks.join("\n")}`,
    filename: `aigently-rules-${input.stackSlug}-${input.ideSlug}.md`,
  };
}

export async function buildSkillMdExport(input: ComposerExportInput & { stackName?: string }) {
  const rules = await listRulesForComposerExport(
    input.stackSlug,
    input.ideSlug,
    input.layers
  );

  const displayName = input.stackName ?? input.stackSlug;
  const frontmatter = [
    "---",
    `name: aigently-${input.stackSlug}-security`,
    `description: Security guardrails for ${displayName} — generated by Aigent.ly`,
    `tags: [security, ${input.stackSlug}]`,
    "---",
    "",
  ].join("\n");

  if (rules.length === 0) {
    return {
      format: "markdown" as const,
      content: `${frontmatter}_No matching rules in the catalog for this configuration._\n`,
      filename: "SKILL.md",
    };
  }

  const body = rules
    .map((r) => (r.bodyMdx ?? "").trim())
    .filter(Boolean)
    .join("\n\n---\n\n");

  return {
    format: "markdown" as const,
    content: `${frontmatter}${body}\n`,
    filename: "SKILL.md",
  };
}
