import { listGuardrailsForComposerExport, listRulesForComposerExport } from "../repos/rulesRepo.js";

export type ComposerExportInput = {
  stackSlug: string;
  ideSlug: string;
  layers: string[];
};

function ideRuleFileExtension(ideSlug: string): "mdc" | "md" {
  // Cursor uses `.mdc` for rule files; others can consume plain markdown.
  return ideSlug === "cursor" ? "mdc" : "md";
}

function isPatternsRuleSlug(slug: string): boolean {
  return /-security-patterns-v\d+$/i.test(slug);
}

function isDepsRuleSlug(slug: string): boolean {
  return /-security-deps-v\d+$/i.test(slug);
}

function globsForDeps(ideSlug: string): string[] {
  // Minimal safe default: only show when editing dependency manifests.
  // (Cursor supports `.mdc` frontmatter; other IDEs still benefit from the intent.)
  if (ideSlug === "cursor") {
    return ["package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "requirements*.txt", "pyproject.toml"];
  }
  return ["package.json", "package-lock.json", "requirements*.txt", "pyproject.toml"];
}

function frontmatterBlock(input: {
  ideSlug: string;
  description: string;
  alwaysApply: boolean;
  globs?: string[];
}) {
  if (ideRuleFileExtension(input.ideSlug) !== "mdc") return "";
  const lines: string[] = ["---", `description: ${input.description}`, `alwaysApply: ${input.alwaysApply}`];
  if (input.globs?.length) {
    lines.push(`globs: [${input.globs.map((g) => JSON.stringify(g)).join(", ")}]`);
  }
  lines.push("---", "");
  return lines.join("\n");
}

export async function buildComposerMarkdownExport(input: ComposerExportInput) {
  const ext = ideRuleFileExtension(input.ideSlug);
  const filename = `aigently-${input.stackSlug}-security.${ext}`;

  // ── Primary path: use per-layer AI-synthesized guardrails ──────────────────
  // These are composable: one section per selected layer, no cross-layer content.
  const guardrails = await listGuardrailsForComposerExport(input.stackSlug, input.layers);

  if (guardrails.length > 0) {
    const layerCount = guardrails.length;
    const fm = frontmatterBlock({
      ideSlug: input.ideSlug,
      description: `${input.stackSlug} security guardrails — ${layerCount} layer${layerCount !== 1 ? "s" : ""}`,
      alwaysApply: true,
    });
    // Each guardrail is a self-contained section; join with a separator.
    const body = guardrails
      .map((g) => g.content.trim())
      .join("\n\n---\n\n");
    return {
      format: "markdown" as const,
      content: `${fm}${body}\n`,
      filename,
    };
  }

  // ── Fallback path: raw rules (used when guardrails haven't been generated yet) ──
  const rules = await listRulesForComposerExport(input.stackSlug, input.ideSlug, input.layers);

  if (rules.length === 0) {
    return {
      format: "markdown" as const,
      content: `<!-- No guardrails or rules found for ${input.stackSlug} with the selected layers. Run the summarize:layers pipeline to generate guardrails. -->\n`,
      filename,
    };
  }

  // Raw rules: emit bodyMdx directly without markdown wrapping so the content
  // reads as AI instructions, not a documentation document.
  const blocks = rules.map((r) => {
    const body = (r.bodyMdx ?? "").trim();
    if (!body) return "";
    const isDeps = isDepsRuleSlug(r.slug);
    const fm = frontmatterBlock({
      ideSlug: input.ideSlug,
      description: r.description,
      alwaysApply: !isDeps,
      globs: isDeps ? globsForDeps(input.ideSlug) : undefined,
    });
    return `${fm}${body}`;
  }).filter(Boolean);

  return {
    format: "markdown" as const,
    content: blocks.join("\n\n---\n\n") + "\n",
    filename,
  };
}

export async function buildSkillMdExport(input: ComposerExportInput & { stackName?: string }) {
  const displayName = input.stackName ?? input.stackSlug;
  const frontmatter = [
    "---",
    `name: aigently-${input.stackSlug}-security`,
    `description: Security guardrails for ${displayName} — generated by Aigent.ly`,
    `tags: [security, ${input.stackSlug}]`,
    "---",
    "",
  ].join("\n");

  // Prefer per-layer guardrails (composable, deduplicated, WHEN/THEN structured)
  const guardrails = await listGuardrailsForComposerExport(input.stackSlug, input.layers);
  if (guardrails.length > 0) {
    const body = guardrails.map((g) => g.content.trim()).filter(Boolean).join("\n\n---\n\n");
    return {
      format: "markdown" as const,
      content: `${frontmatter}${body}\n`,
      filename: "SKILL.md",
    };
  }

  // Fallback to raw rules
  const rules = await listRulesForComposerExport(input.stackSlug, input.ideSlug, input.layers);
  if (rules.length === 0) {
    return {
      format: "markdown" as const,
      content: `${frontmatter}<!-- No guardrails or rules found. Run summarize:layers to generate content. -->\n`,
      filename: "SKILL.md",
    };
  }

  const body = rules.map((r) => (r.bodyMdx ?? "").trim()).filter(Boolean).join("\n\n---\n\n");
  return {
    format: "markdown" as const,
    content: `${frontmatter}${body}\n`,
    filename: "SKILL.md",
  };
}
